import localFont from "next/font/local";
import "@/styles/base.scss";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const helvetica = localFont({
  src: [
    {
      path: "./fonts/Helvetica-Bold.woff",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/Helvetica.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Helvetica-light.woff",
      weight: "300",
      style: "normal",
    },
  ],
  display: "swap",
  variable: "--font-helvetica",
});

const helveticaNeue = localFont({
  src: [
    {
      path: "./fonts/HelveticaNeue-Medium.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNeue-Thin.woff",
      weight: "300",
      style: "normal",
    },
  ],
  display: "swap",
  variable: "--font-helvetica-neue",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

console.log(helveticaNeue.variable);

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${helvetica.variable} ${helveticaNeue.variable}`}
    >
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
